### ISSUE TITLE
Add a co-maintainer?

### ISSUE THREAD

**Issue by mburns** [sboschert/chef-cookbook-docker_compose#12]
Hi @sboschert,

Looks like this cookbook isn't getting maintained. Are you open to adding me as a maintainer so I can land some open PRs and keep this cookbook working in newer versions of the various tools?

Cheers!

**Comment by sboschert** [comment]
Hey,

somehow I didn't get notifications for the pending PRs. I'll look into them in the next few days.

Sorry for the delay...

- Sebastian

**Comment by sboschert** [comment]
Michael,

last summer you offered to be a co-maintainer on this project. Would you still be up for it? Unfortunately my time has gotten really scarce over the last year and I guess I could use some help here.

Take care,
Sebastian

**Comment by mburns** [comment]
Hey @sboschert I'd be happy to lend a hand!

**Comment by sboschert** [comment]
I added you. You should have received an invitation.

**Comment by sboschert** [comment]
Alright, I guess I can close this issue.
